version: '3'

services:
  config-server:
    build:
      context: ./config-server
    expose: 
      - 8000
    env_file: 
      - env_${DEPLOY_ENV}.env

  discovery:
    build:
      context: ./discovery-server
    env_file: env_${DEPLOY_ENV}.env
    expose: 
       - 8001
    ports:
      - "8001:8001"
    depends_on: 
      - config-server
    entrypoint: 
      - ./wait
      - config-server:8000
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar
  
  gateway:
    build:
      context: ./gateway
    env_file: env_${DEPLOY_ENV}.env
    expose: 
       - 8080
    ports:
      - "8080:8080"
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar
  
  user-service:
    build:
      context: ./gablum-user-management
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar
  
  webapp:
    build:
      context: ./gablum-webapp
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  rabbit:
    image: rabbitmq:3.8.1-alpine
    depends_on: 
      - discovery

  auctions:
    build:
      context: ./gablum-auction/auctions
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  bid:
    build:
      context: ./gablum-auction/bid
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  proposals:
    build:
      context: ./gablum-proposals
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  scheduler:
    build:
      context: ./gablum-scheduler
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  contracts:
    build:
      context: ./gablum-contracts
    env_file: env_${DEPLOY_ENV}.env
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/app.jar